---
- name: Configure EC2 instances
  hosts: tag_Name_web-server*
  become: true
  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Set up custom index.html
      copy:
        content: "Hostname or IP: {{ ansible_default_ipv4.address }}"
        dest: /usr/share/nginx/html/index.html
      notify: restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted